"use client";
import { Metadata } from "next";
import { Layout } from "antd";
import "./globals.css";
import { layoutStyle } from "./util/cssstyle";

export const metadata: Metadata = {
  title: "Frontend Mentor | Newsletter sign-up form with success message",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout style={layoutStyle}>{children}</Layout>
      </body>
    </html>
  );
}
