name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Github Pages Deploy Action
        uses: avinal/github-pages-deploy-action@v0.9
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PAGES_BRANCH: gh-pages
          BUILD_FROM: main # 배포될 브랜치
          DOCS_FOLDER: out # 이 폴더에 있는 파일을 배포
